services:
  web:
    build: backend
    env_file:
      - .prod.env
    ports:
      - "8000:8000"
    restart: always


  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - web
    restart: always